### PR TITLE
Add which to c3i-linux-ppc64le

### PR DESCRIPTION
**Pull request by nehaljwani**

### CODE REVIEW

**Comment by mingwandroid** [comment]
Guys, why? This which binary has *serious* bugs in it.

**Comment by nehaljwani** [comment]
@mingwandroid I saw some build systems failing, example output:
```
+GXX=/root/worker/containers/000007vuhkg/tmp/build/80754af9/nodejs_1522820545377/_build_env/bin/powerpc64le-conda_cos7-linux-gnu-g++	
./configure: line 1: which: command not found	
./configure: line 2: which: command not found	
creating icu_config.gypi
```

**Comment by msarahan** [comment]
happy to remove if the bugs are worse than not having it.

**Comment by mingwandroid** [comment]
Hmm, well, the problem with this exact which on ppc64le is that it fails to find anything in a path with more than 256 characters.

Maybe we need to build our own more up to date one and depend upon that when necessary?

**Comment by jjhelmus** [comment]
I have been using type in place of which is recipe because of the limit but that doesn't fix the issue with build tools using which.

**Pull request merged**
