### PR TITLE
transfer concourse-rsync-resource image to conda org

### PR DESCRIPTION
**Pull request by msarahan**

### CODE REVIEW

**Comment by msarahan** [comment]
CC @nehaljwani @jjhelmus @mingwandroid - right now, both of these images are the same.  Going forward, only the new location on the conda repo will be updated.

**Comment by nehaljwani** [comment]
Which repo holds the contents of the Docker Image?

**Comment by msarahan** [comment]
https://github.com/conda/concourse-rsync-resource

**Comment by msarahan** [comment]
build at https://cloud.docker.com/swarm/conda/repository/docker/conda/concourse-rsync-resource/builds

**Pull request merged**
