### PR TITLE
add c3i rm command to make pipeline cleanup faster

### PR DESCRIPTION
**Pull request by msarahan**
cc @jjhelmus @nehaljwani

### CODE REVIEW

**Comment by jjhelmus** [comment]
any chance this could take a glob?  Then I could do `c3i rm "jjh*"`?

**Comment by msarahan** [comment]
That requires introspection of what exists on the server.  It's probably possible.

```
fly -t 35 ps
name                 paused  public
c3i_docker           no      no
navigator            no      yes
test-rdonnelly       no      yes
mac_test             no      yes
nwani                no      yes
kale-one-off         no      yes
nwani_win            no      yes
nwani_linux-32       no      yes
conda-feedstock      no      yes
nwani_osx            no      yes
postgresql           no      yes
postgresql_win       no      yes
nwani_2              no      yes
nwani_linux-ppc64le  no      yes
nwani_linux-64       no      yes
rdonnelly-cb         no      yes
np113_mklfft_linux   no      yes
rdonnelly            no      yes
tbb                  no      yes
numpy-win-test       no      yes
tag_test             no      no
jjh_tornado          no      yes
jjh_scipy            no      yes
jjh_curl             no      yes
jjh_unixodbc         no      yes
jjh_curl_ppc         no      yes
jjh_unixodbc_ppc     no      yes
jjh_boto3            no      yes
```

A glob could then be added to loop over matching names

**Comment by jjhelmus** [comment]
Interesting.  Not sure if this needs to be in c3i or if a bash script which calls fly would be sufficient.  Either way not a high priority.

**Comment by msarahan** [comment]
Probably better in c3i, since all the connection details are already handled there.  I'll look into it.

**Pull request merged**
