### PR TITLE
Add support for compiling 32-bit packages on 64-bit container

### PR DESCRIPTION
**Pull request by nehaljwani**

### CODE REVIEW

**Comment by msarahan** [comment]
Please ping me when this is all ready to go, and I'll be happy to merge it.  You should probably also remove the old linux-32 dockerfile.

**Comment by nehaljwani** [comment]
Do you really want me to delete it, or add a README stating do not use this!

**Comment by msarahan** [comment]
Probably delete it, so that we aren't triggering builds of something that isn't actually used.  If we need it in the future, we can just get it from the git history.

**Comment by nehaljwani** [comment]
Finally, all tests pass! Wohoo!!!

@msarahan before merging this, please double check that I am doing the right thing at https://github.com/conda/conda-concourse-ci/pull/61/commits/a45a7aea60107a058d6dc4ca1892212da1c0f23d

**Comment by msarahan** [comment]
Thanks @nehaljwani - all looks good to me. After this, we'll still need to tweak the conda build command so that it gets run with linux32, right?

Do you have plans for how to do that?

**Comment by nehaljwani** [comment]
I was wondering, is there any downside to always prepend: 
```
export CONDA_SUBDIR="{}-{}".format(worker['platform'], worker['arch'])
```
... just before the `conda update -y conda-build`, irrespective of the build?

**Comment by msarahan** [comment]
I don't see any downside off the top of my head, but please try it and make sure that nothing unexpected happens.  The only potential thing I see happening is that it may break some of the stuff that merges build and host together when the target_platform matches the native subdir.  That stuff *should* work, but might have some unforeseen flaws.

**Pull request merged**
