### PR TITLE
We need PAM system libs for pamela

### PR DESCRIPTION
**Pull request by mingwandroid**
(Not my wife, she does not have much time for geeky stuff).

### CODE REVIEW

**Comment by msarahan** [comment]
Is this the right place, or should PAM be a CDT package?

**Comment by mingwandroid** [comment]
You need both, one to build against, one to test against (pamela runs some tests). The pam CDT packages are already available.

**Comment by msarahan** [comment]
👍

**Comment by mingwandroid** [comment]
Thanks @msarahan, how does deployment happen for these, is it automatic?

**Comment by msarahan** [comment]
yes, new images are built automatically.  They'll be used once they are uploaded.  This is the concourse pipeline that takes care of it: https://concourse.build.corp.continuum.io/teams/main/pipelines/c3i_docker

**Pull request merged**
